name: CI - Maven and Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maven:
    name: Maven build and run (Java 21)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Show Java info
        run: java -version && echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}"

      - name: Build with Maven
        run: mvn -U -B package
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Run demo (Maven)
        run: mvn -q exec:java -Dexec.mainClass=org.example.Main
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

  gradle:
    name: Gradle build and run (Java 21)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        id: setup-java-gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Show Java info
        run: java -version && echo "JAVA_HOME=${{ steps.setup-java-gradle.outputs.java-home }}"

      - name: Use Gradle wrapper (show version)
        run: ./gradlew --version
        env:
          JAVA_HOME: ${{ steps.setup-java-gradle.outputs.java-home }}

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
        env:
          JAVA_HOME: ${{ steps.setup-java-gradle.outputs.java-home }}

      - name: Run demo (Gradle)
        run: ./gradlew run --no-daemon
        env:
          JAVA_HOME: ${{ steps.setup-java-gradle.outputs.java-home }}
